//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachImageWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class aRecipe
    {
        [Display(Name = "食譜編號")]
        public int aId { get; set; }
        [Display(Name = "食譜名稱")]
        public string aName { get; set; }
        [Display(Name = "食譜類別")]
        public int classId { get; set; }
        [Display(Name = "食譜介紹")]
        public string aIntroduce { get; set; }
        [Display(Name = "食譜照片")]
        public string aImg { get; set; }
        [Display(Name = "數量")]
        public int aQuantity { get; set; }
        [Display(Name = "時間")]
        public int aTime { get; set; }
        [Display(Name = "會員編號")]
        public int cId { get; set; }
        
    }
}
